Feature: Get Configuration
  #@report=false

  Background:  Check for Schema
     # Set the Auth credentials here
    * configure headers = read('data/headers.js')
    # Change the environment for other API
    * def ENV = 'v1'
	#* def data = read('classpath:data/myData.json')
	#* def myConfig = read('classpath:schema/schema_config.json#/definitions/myConfig')

  Scenario: Make a request with custom Basic Auth credentials
    Given url 'https://api-beta.lightmetrics.co'+'/v1/configuration'
    When method GET
    Then status 200
    And print response
	   #And match response.[1] ==''
	   #And def myConfig = response.myJsonPathExpression
	   #And match each myConfig

  Scenario: Get Fleet Configurations
    Given url 'https://api-beta.lightmetrics.co'+'/v1/fleets/qatest001/configuration'
    When method GET
    Then status 200
    And print response

  Scenario: Get Asset Configurations
    Given url 'https://api-beta.lightmetrics.co'+'/v1/fleets/qatest001/configuration/353436105011125'
    When method GET
    Then status 200
    And print response

  @ignore
  Scenario Outline: Make a request with Requests for Common Config
  #TODO - to add a CSV file externally
    Given url 'https://api-beta.lightmetrics.co'+'/v1/fleets/qatest002/configuration'
    And request { "configuration":{"light": {'<Key>': <value>  } } }
    #{"configuration":}{: '#(<name>)', country: '#(country)', active: '#(active)', limit: '#(limit)'
    When method PATCH
    Then status 200
    And print response
    Examples:
      | Key                                                           | value                |
      | allowWifiDirectConfigUpdate                                   | true                 |
      | allowWifiDirectConfigUpdate                                   | false                |
      | anomalyEDVREnabled                                            | true                 |
      | anomalyEDVREnabled                                            | false                |
      | anomalyEnabled                                                | true                 |
      | anomalyEnabled                                                | false                |
      | anomalyEventVideoType                                         | pictureInPicture     |
      | anomalyEventVideoType                                         | sideBySide           |
      | anomalyThreshold                                              | 0                    |
      | anomalyThreshold                                              | 20                   |
      | APNSwitchSupported                                            | true                 |
      | APNSwitchSupported                                            | false                |
      | captureImageOnWarningTailgating                               | true                 |
      | captureImageOnWarningTailgating                               | false                |
      | captureMediaOnEventAnomaly                                    | true                 |
      | captureMediaOnEventAnomaly                                    | false                |
      | captureMediaOnEventCellphoneDistraction                       | true                 |
      | captureMediaOnEventCellphoneDistraction                       | false                |
      | captureMediaOnEventCornering                                  | true                 |
      | captureMediaOnEventCornering                                  | false                |
      | captureMediaOnEventDistractedDriving                          | true                 |
      | captureMediaOnEventDistractedDriving                          | false                |
      | captureMediaOnEventDrowsyDriving                              | true                 |
      | captureMediaOnEventDrowsyDriving                              | false                |
      | captureMediaOnEventForwardCollisionWarning                    | true                 |
      | captureMediaOnEventForwardCollisionWarning                    | false                |
      | captureMediaOnEventHardBraking                                | true                 |
      | captureMediaOnEventHardBraking                                | false                |
      | captureMediaOnEventHarshAcceleration                          | true                 |
      | captureMediaOnEventHarshAcceleration                          | false                |
      | captureMediaOnEventLaneDeparture                              | true                 |
      | captureMediaOnEventLaneDeparture                              | false                |
      | captureMediaOnEventLaneDrift                                  | true                 |
      | captureMediaOnEventLaneDrift                                  | false                |
      | captureMediaOnEventMaxSpeed                                   | true                 |
      | captureMediaOnEventMaxSpeed                                   | false                |
      | captureMediaOnEventPotentialCrash                             | true                 |
      | captureMediaOnEventPotentialCrash                             | false                |
      | captureMediaOnEventSpeeding                                   | true                 |
      | captureMediaOnEventSpeeding                                   | false                |
      | captureMediaOnEventStopSignViolation                          | true                 |
      | captureMediaOnEventStopSignViolation                          | false                |
      | captureMediaOnEventTailgating                                 | true                 |
      | captureMediaOnEventTailgating                                 | false                |
      | cellphoneDistractionEDVREnabled                               | true                 |
      | cellphoneDistractionEDVREnabled                               | false                |
      | cellphoneDistractionEventVideoType                            | pictureInPicture     |
      | cellphoneDistractionEventVideoType                            | sideBySide           |
      | companionConnectionNotificationLEDAltColor                    | green                |
      | companionConnectionNotificationLEDAltColor                    | yellow               |
      | companionConnectionNotificationLEDAltPulseDuration            | 10                   |
      | companionConnectionNotificationLEDAltPulseDuration            | 60000                |
      | companionConnectionNotificationLEDColor                       | green                |
      | companionConnectionNotificationLEDColor                       | yellow               |
      | companionConnectionNotificationLEDMode                        | pulse                |
      | companionConnectionNotificationLEDMode                        | constant             |
      | companionConnectionNotificationLEDPulseDuration               | 10                   |
      | companionConnectionNotificationLEDPulseDuration               | 20000                |
      | corneringEDVREnabled                                          | true                 |
      | corneringEDVREnabled                                          | false                |
      | corneringEnabled                                              | true                 |
      | corneringEnabled                                              | false                |
      | corneringEventVideoType                                       | pictureInPicture     |
      | corneringEventVideoType                                       | sideBySide           |
      | corneringThreshold                                            | 1                    |
      | corneringThreshold                                            | 20                   |
      | customEventImageEnabled                                       | true                 |
      | customEventImageEnabled                                       | false                |
      | customEventImageVideoType                                     | separate             |
      | customEventImageVideoType                                     | pictureInPicture     |
      | customEventsEDVREnabled                                       | true                 |
      | customEventsEDVREnabled                                       | false                |
      | customEventsEventVideoType                                    | pictureInPicture     |
      | customEventsEventVideoType                                    | sideBySide           |
      | customEventVideoEnabled                                       | true                 |
      | customEventVideoEnabled                                       | false                |
      | debugMediaDataTransfer                                        | high                 |
      | debugMediaDataTransfer                                        | low                  |
      | debugMediaDataTransfer                                        | medium               |
      | defaultDriverSeatSide                                         | left                 |
      | defaultDriverSeatSide                                         | right                |
      | defaultLanguageCode                                           | en-US                |
      | defaultLanguageCode                                           | pt-BR                |
      | defaultLanguageCode                                           | en-GB                |
      | defaultLanguageCode                                           | fr-CA                |
      | defaultRoadSignsType                                          | Vienna               |
      | defaultRoadSignsType                                          | Australia            |
      | defaultRoadSignUnits                                          | mph                  |
      | defaultRoadSignUnits                                          | kmph                 |
      | deviceAudioVolume                                             | 0                    |
      | deviceAudioVolume                                             | 15                   |
      | deviceButtonSingleClickFunction                               | LANGUAGE_SELECT      |
      | deviceButtonSingleClickFunction                               | CUSTOM_EVENT_CAPTURE |
      | distractedDrivingEDVREnabled                                  | true                 |
      | distractedDrivingEDVREnabled                                  | false                |
      | distractedDrivingEnabled                                      | true                 |
      | distractedDrivingEnabled                                      | false                |
      | distractedDrivingEventVideoType                               | pictureInPicture     |
      | distractedDrivingEventVideoType                               | sideBySide           |
      | driverIdSource                                                | wifiDirect           |
      | driverIdSource                                                | faceRecognition      |
      | driverPersistenceEnabled                                      | true                 |
      | driverPersistenceEnabled                                      | false                |
      | drowsinessThreshold                                           | 50                   |
      | drowsinessThreshold                                           | 70                   |
      | drowsyDrivingEDVREnabled                                      | true                 |
      | drowsyDrivingEDVREnabled                                      | false                |
      | drowsyDrivingEnabled                                          | true                 |
      | drowsyDrivingEnabled                                          | false                |
      | drowsyDrivingEventVideoType                                   | pictureInPicture     |
      | drowsyDrivingEventVideoType                                   | sideBySide           |
      | dvrStoredVideoFramesPerSecondDriver                           | 10                   |
      | dvrStoredVideoFramesPerSecondDriver                           | 30                   |
      | dvrStoredVideoFramesPerSecondRoad                             | 10                   |
      | dvrStoredVideoFramesPerSecondRoad                             | 30                   |
      | dvrStoredVideoResolutionDriver                                | 1280x720             |
      | dvrStoredVideoResolutionRoad                                  | 1280x720             |
      | dvrStoredVideoResolutionRoad                                  | 1920x1080            |
      | edvrStorageDuration                                           | 0                    |
      | edvrStorageDuration                                           | 10                   |
      | enableCellphoneDistraction                                    | true                 |
      | enableCellphoneDistraction                                    | false                |
      | enableCrowdsourcedSpeedsigns                                  | true                 |
      | enableCrowdsourcedSpeedsigns                                  | false                |
      | enableDrinkingWhileDrivingDistraction                         | true                 |
      | enableDrinkingWhileDrivingDistraction                         | false                |
      | enableDriverCamera                                            | true                 |
      | enableDriverCamera                                            | false                |
      | enableFRDriverIdentification                                  | true                 |
      | enableFRDriverIdentification                                  | false                |
      | enableFRExperimentation                                       | true                 |
      | enableFRExperimentation                                       | false                |
      | enableLiveTelematics                                          | true                 |
      | enableLiveTelematics                                          | false                |
      | enableMediaTextInscription                                    | true                 |
      | enableMediaTextInscription                                    | false                |
      | enableNotificationLED                                         | true                 |
      | enableNotificationLED                                         | false                |
      | enablePassiveMode                                             | true                 |
      | enablePassiveMode                                             | false                |
      | enableSmokingWhileDrivingDistraction                          | true                 |
      | enableSmokingWhileDrivingDistraction                          | false                |
      | enableSystemLogs                                              | true                 |
      | enableSystemLogs                                              | false                |
      | enableTextingWhileDrivingDistraction                          | true                 |
      | enableTextingWhileDrivingDistraction                          | false                |
      | eventImageQuality                                             | 0                    |
      | eventImageQuality                                             | 10                   |
      | eventImageResolution                                          | 320x180              |
      | eventImageResolution                                          | 1920x1080            |
      | eventMediaTypeCellphoneDistraction                            | video                |
      | eventMediaTypeCellphoneDistraction                            | image                |
      | eventMediaTypeCornering                                       | video                |
      | eventMediaTypeCornering                                       | image                |
      | eventMediaTypeForwardCollisionWarning                         | video                |
      | eventMediaTypeForwardCollisionWarning                         | image                |
      | eventMediaTypeHardBraking                                     | video                |
      | eventMediaTypeHardBraking                                     | image                |
      | eventMediaTypeHarshAcceleration                               | video                |
      | eventMediaTypeHarshAcceleration                               | image                |
      | eventMediaTypeLaneDeparture                                   | video                |
      | eventMediaTypeLaneDeparture                                   | image                |
      | eventMediaTypeLaneDrift                                       | video                |
      | eventMediaTypeLaneDrift                                       | image                |
      | eventMediaTypeMaxSpeed                                        | video                |
      | eventMediaTypeMaxSpeed                                        | image                |
      | eventMediaTypePotentialCrash                                  | video                |
      | eventMediaTypePotentialCrash                                  | image                |
      | eventMediaTypeSpeeding                                        | video                |
      | eventMediaTypeSpeeding                                        | image                |
      | eventVideoDriverCameraQualityAnomaly                          | 0                    |
      | eventVideoDriverCameraQualityAnomaly                          | 10                   |
      | eventVideoDriverCameraQualityCellphoneDistraction             | 0                    |
      | eventVideoDriverCameraQualityCellphoneDistraction             | 10                   |
      | eventVideoDriverCameraQualityCornering                        | 0                    |
      | eventVideoDriverCameraQualityCornering                        | 10                   |
      | eventVideoDriverCameraQualityCustomEvents                     | 0                    |
      | eventVideoDriverCameraQualityCustomEvents                     | 10                   |
      | eventVideoDriverCameraQualityDistractedDriving                | 0                    |
      | eventVideoDriverCameraQualityDistractedDriving                | 10                   |
      | eventVideoDriverCameraQualityDrowsyDriving                    | 0                    |
      | eventVideoDriverCameraQualityDrowsyDriving                    | 10                   |
      | eventVideoDriverCameraQualityForwardCollisionWarning          | 0                    |
      | eventVideoDriverCameraQualityForwardCollisionWarning          | 10                   |
      | eventVideoDriverCameraQualityHardBraking                      | 0                    |
      | eventVideoDriverCameraQualityHardBraking                      | 10                   |
      | eventVideoDriverCameraQualityHarshAcceleration                | 0                    |
      | eventVideoDriverCameraQualityHarshAcceleration                | 10                   |
      | eventVideoDriverCameraQualityLaneDeparture                    | 0                    |
      | eventVideoDriverCameraQualityLaneDeparture                    | 10                   |
      | eventVideoDriverCameraQualityLaneDrift                        | 0                    |
      | eventVideoDriverCameraQualityLaneDrift                        | 10                   |
      | eventVideoDriverCameraQualityMaxSpeed                         | 0                    |
      | eventVideoDriverCameraQualityMaxSpeed                         | 10                   |
      | eventVideoDriverCameraQualityPotentialCrash                   | 0                    |
      | eventVideoDriverCameraQualityPotentialCrash                   | 10                   |
      | eventVideoDriverCameraQualitySpeeding                         | 0                    |
      | eventVideoDriverCameraQualitySpeeding                         | 10                   |
      | eventVideoDriverCameraQualityStopSignViolation                | 0                    |
      | eventVideoDriverCameraQualityStopSignViolation                | 10                   |
      | eventVideoDriverCameraQualityTailgating                       | 0                    |
      | eventVideoDriverCameraQualityTailgating                       | 10                   |
      | eventVideoDriverCameraResolutionAnomaly                       | 320x180              |
      | eventVideoDriverCameraResolutionAnomaly                       | 1280x720             |
      | eventVideoDriverCameraResolutionCellphoneDistraction          | 320x180              |
      | eventVideoDriverCameraResolutionCellphoneDistraction          | 1280x720             |
      | eventVideoDriverCameraResolutionCornering                     | 320x180              |
      | eventVideoDriverCameraResolutionCornering                     | 1280x720             |
      | eventVideoDriverCameraResolutionCustomEvents                  | 320x180              |
      | eventVideoDriverCameraResolutionCustomEvents                  | 1280x720             |
      | eventVideoDriverCameraResolutionDistractedDriving             | 320x180              |
      | eventVideoDriverCameraResolutionDistractedDriving             | 1280x720             |
      | eventVideoDriverCameraResolutionDrowsyDriving                 | 320x180              |
      | eventVideoDriverCameraResolutionDrowsyDriving                 | 1280x720             |
      | eventVideoDriverCameraResolutionForwardCollisionWarning       | 320x180              |
      | eventVideoDriverCameraResolutionForwardCollisionWarning       | 1280x720             |
      | eventVideoDriverCameraResolutionHardBraking                   | 320x180              |
      | eventVideoDriverCameraResolutionHardBraking                   | 1280x720             |
      | eventVideoDriverCameraResolutionHarshAcceleration             | 320x180              |
      | eventVideoDriverCameraResolutionHarshAcceleration             | 640x360              |
      | eventVideoDriverCameraResolutionHarshAcceleration             | 1280x720             |
      | eventVideoDriverCameraResolutionLaneDeparture                 | 320x180              |
      | eventVideoDriverCameraResolutionLaneDeparture                 | 1280x720             |
      | eventVideoDriverCameraResolutionLaneDrift                     | 320x180              |
      | eventVideoDriverCameraResolutionLaneDrift                     | 1280x720             |
      | eventVideoDriverCameraResolutionMaxSpeed                      | 320x180              |
      | eventVideoDriverCameraResolutionMaxSpeed                      | 1280x720             |
      | eventVideoDriverCameraResolutionPotentialCrash                | 320x180              |
      | eventVideoDriverCameraResolutionPotentialCrash                | 1280x720             |
      | eventVideoDriverCameraResolutionSpeeding                      | 320x180              |
      | eventVideoDriverCameraResolutionSpeeding                      | 1280x720             |
      | eventVideoDriverCameraResolutionStopSignViolation             | 320x180              |
      | eventVideoDriverCameraResolutionStopSignViolation             | 1280x720             |
      | eventVideoDriverCameraResolutionTailgating                    | 320x180              |
      | eventVideoDriverCameraResolutionTailgating                    | 1280x720             |
      | eventVideoQualityAnomaly                                      | 0                    |
      | eventVideoQualityAnomaly                                      | 10                   |
      | eventVideoQualityCellphoneDistraction                         | 0                    |
      | eventVideoQualityCellphoneDistraction                         | 10                   |
      | eventVideoQualityCornering                                    | 0                    |
      | eventVideoQualityCornering                                    | 10                   |
      | eventVideoQualityCustomEvents                                 | 0                    |
      | eventVideoQualityCustomEvents                                 | 10                   |
      | eventVideoQualityDistractedDriving                            | 0                    |
      | eventVideoQualityDistractedDriving                            | 10                   |
      | eventVideoQualityDrowsyDriving                                | 0                    |
      | eventVideoQualityDrowsyDriving                                | 10                   |
      | eventVideoQualityForwardCollisionWarning                      | 0                    |
      | eventVideoQualityForwardCollisionWarning                      | 10                   |
      | eventVideoQualityHardBraking                                  | 0                    |
      | eventVideoQualityHardBraking                                  | 10                   |
      | eventVideoQualityHarshAcceleration                            | 0                    |
      | eventVideoQualityHarshAcceleration                            | 10                   |
      | eventVideoQualityLaneDeparture                                | 0                    |
      | eventVideoQualityLaneDeparture                                | 10                   |
      | eventVideoQualityLaneDrift                                    | 0                    |
      | eventVideoQualityLaneDrift                                    | 10                   |
      | eventVideoQualityMaxSpeed                                     | 0                    |
      | eventVideoQualityMaxSpeed                                     | 10                   |
      | eventVideoQualityPotentialCrash                               | 0                    |
      | eventVideoQualityPotentialCrash                               | 10                   |
      | eventVideoQualitySpeeding                                     | 0                    |
      | eventVideoQualitySpeeding                                     | 10                   |
      | eventVideoQualityStopSignViolation                            | 0                    |
      | eventVideoQualityStopSignViolation                            | 10                   |
      | eventVideoQualityTailgating                                   | 0                    |
      | eventVideoQualityTailgating                                   | 10                   |
      | eventVideoResolutionAnomaly                                   | 320x180              |
      | eventVideoResolutionAnomaly                                   | 1920x1080            |
      | eventVideoResolutionCellphoneDistraction                      | 320x180              |
      | eventVideoResolutionCellphoneDistraction                      | 1920x1080            |
      | eventVideoResolutionCornering                                 | 320x180              |
      | eventVideoResolutionCornering                                 | 1920x1080            |
      | eventVideoResolutionCustomEvents                              | 320x180              |
      | eventVideoResolutionCustomEvents                              | 1920x1080            |
      | eventVideoResolutionDistractedDriving                         | 320x180              |
      | eventVideoResolutionDistractedDriving                         | 1920x1080            |
      | eventVideoResolutionDrowsyDriving                             | 320x180              |
      | eventVideoResolutionDrowsyDriving                             | 1920x1080            |
      | eventVideoResolutionForwardCollisionWarning                   | 320x180              |
      | eventVideoResolutionForwardCollisionWarning                   | 1920x1080            |
      | eventVideoResolutionHardBraking                               | 320x180              |
      | eventVideoResolutionHardBraking                               | 1920x1080            |
      | eventVideoResolutionHarshAcceleration                         | 320x180              |
      | eventVideoResolutionHarshAcceleration                         | 1920x1080            |
      | eventVideoResolutionLaneDeparture                             | 320x180              |
      | eventVideoResolutionLaneDeparture                             | 1920x1080            |
      | eventVideoResolutionLaneDrift                                 | 320x180              |
      | eventVideoResolutionLaneDrift                                 | 1920x1080            |
      | eventVideoResolutionMaxSpeed                                  | 320x180              |
      | eventVideoResolutionMaxSpeed                                  | 1920x1080            |
      | eventVideoResolutionPotentialCrash                            | 320x180              |
      | eventVideoResolutionPotentialCrash                            | 1920x1080            |
      | eventVideoResolutionSpeeding                                  | 320x180              |
      | eventVideoResolutionSpeeding                                  | 1920x1080            |
      | eventVideoResolutionStopSignViolation                         | 320x180              |
      | eventVideoResolutionStopSignViolation                         | 1920x1080            |
      | eventVideoResolutionTailgating                                | 320x180              |
      | eventVideoResolutionTailgating                                | 1920x1080            |
      | forceApplyNewAssetConfig                                      | true                 |
      | forceApplyNewAssetConfig                                      | false                |
      | forwardCollisionWarningEDVREnabled                            | true                 |
      | forwardCollisionWarningEDVREnabled                            | false                |
      | forwardCollisionWarningEnabled                                | true                 |
      | forwardCollisionWarningEnabled                                | false                |
      | forwardCollisionWarningEventVideoType                         | pictureInPicture     |
      | forwardCollisionWarningEventVideoType                         | sideBySide           |
      | forwardCollisionWarningTTCThreshold                           | 0.25                 |
      | forwardCollisionWarningTTCThreshold                           | 3                    |
      | gpsLocationCaptureFrequency                                   | high                 |
      | gpsLocationCaptureFrequency                                   | low                  |
      | gSensorIgnitionOffConfirmationDurationSeconds                 | 120                  |
      | gSensorIgnitionOffConfirmationDurationSeconds                 | 600                  |
      | gSensorIgnitionOffConfirmationSpeedMph                        | 0                    |
      | gSensorIgnitionOffConfirmationSpeedMph                        | 20                   |
      | gSensorSampleSize                                             | 1                    |
      | gSensorSampleSize                                             | 4                    |
      | gSensorSamplingPeriodMillis                                   | 10                   |
      | gSensorSamplingPeriodMillis                                   | 2000                 |
      | gSensorShortTripDistanceThresholdMiles                        | 0                    |
      | gSensorShortTripDistanceThresholdMiles                        | 10                   |
      | gSensorShortTripTimeThresholdSeconds                          | 120                  |
      | gSensorShortTripTimeThresholdSeconds                          | 300                  |
      | gSensorThreshold                                              | 0.01                 |
      | gSensorThreshold                                              | 0.627                |
      | hardBrakingEDVREnabled                                        | true                 |
      | hardBrakingEDVREnabled                                        | false                |
      | hardBrakingEnabled                                            | true                 |
      | hardBrakingEnabled                                            | false                |
      | hardBrakingEventVideoType                                     | pictureInPicture     |
      | hardBrakingEventVideoType                                     | sideBySide           |
      | hardBrakingThreshold                                          | 1                    |
      | hardBrakingThreshold                                          | 20                   |
      | harshAccelerationEDVREnabled                                  | true                 |
      | harshAccelerationEDVREnabled                                  | false                |
      | harshAccelerationEnabled                                      | true                 |
      | harshAccelerationEnabled                                      | false                |
      | harshAccelerationEventVideoType                               | road                 |
      | harshAccelerationEventVideoType                               | separate             |
      | harshAccelerationEventVideoType                               | pictureInPicture     |
      | harshAccelerationEventVideoType                               | driver               |
      | harshAccelerationEventVideoType                               | sideBySide           |
      | harshAccelerationThreshold                                    | 1                    |
      | harshAccelerationThreshold                                    | 20                   |
      | idleNotificationLEDAltColor                                   | green                |
      | idleNotificationLEDAltColor                                   | yellow               |
      | idleNotificationLEDAltPulseDuration                           | 10                   |
      | idleNotificationLEDAltPulseDuration                           | 20000                |
      | idleNotificationLEDColor                                      | green                |
      | idleNotificationLEDColor                                      | yellow               |
      | idleNotificationLEDMode                                       | constant             |
      | idleNotificationLEDMode                                       | pulse                |
      | idleNotificationLEDPulseDuration                              | 10                   |
      | idleNotificationLEDPulseDuration                              | 20000                |
      | ignitionOffNotificationLEDAltColor                            | green                |
      | ignitionOffNotificationLEDAltColor                            | yellow               |
      | ignitionOffNotificationLEDAltPulseDuration                    | 10                   |
      | ignitionOffNotificationLEDAltPulseDuration                    | 20000                |
      | ignitionOffNotificationLEDColor                               | green                |
      | ignitionOffNotificationLEDColor                               | yellow               |
      | ignitionOffNotificationLEDMode                                | pulse                |
      | ignitionOffNotificationLEDMode                                | constant             |
      | ignitionOffNotificationLEDPulseDuration                       | 10                   |
      | ignitionOffNotificationLEDPulseDuration                       | 20000                |
      | ignoreSchoolZoneSpeedingViolations                            | true                 |
      | ignoreSchoolZoneSpeedingViolations                            | false                |
      | infraredLEDMode                                               | on                   |
      | infraredLEDMode                                               | off                  |
      | instantlyPushViolations                                       | true                 |
      | instantlyPushViolations                                       | false                |
      | laneDepartureEDVREnabled                                      | true                 |
      | laneDepartureEDVREnabled                                      | false                |
      | laneDepartureEnabled                                          | true                 |
      | laneDepartureEnabled                                          | false                |
      | laneDepartureEventVideoType                                   | pictureInPicture     |
      | laneDepartureEventVideoType                                   | sideBySide           |
      | laneDepartureThreshold                                        | 0                    |
      | laneDepartureThreshold                                        | 10                   |
      | laneDriftEDVREnabled                                          | true                 |
      | laneDriftEDVREnabled                                          | false                |
      | laneDriftEnabled                                              | true                 |
      | laneDriftEnabled                                              | false                |
      | laneDriftEventVideoType                                       | pictureInPicture     |
      | laneDriftEventVideoType                                       | sideBySide           |
      | laneDriftSensitivity                                          | 0                    |
      | laneDriftSensitivity                                          | 10                   |
      | liveTelematicsPushFrequencySeconds                            | 30                   |
      | liveTelematicsPushFrequencySeconds                            | 60                   |
      | lowDataTransferMode                                           | true                 |
      | lowDataTransferMode                                           | false                |
      | maxSpeedEDVREnabled                                           | true                 |
      | maxSpeedEDVREnabled                                           | false                |
      | maxSpeedEnabled                                               | true                 |
      | maxSpeedEnabled                                               | false                |
      | maxSpeedEventVideoType                                        | pictureInPicture     |
      | maxSpeedEventVideoType                                        | sideBySide           |
      | mediaTextInscriptionDateFormat                                | dd-MM-yyyy           |
      | mediaTextInscriptionDateFormat                                | yyyy-MM-dd           |
      | mediaTextInscriptionDateFormat                                | MM-dd-yyyy           |
      | mediaUploadMinimumSeverityAnomaly                             | 0                    |
      | mediaUploadMinimumSeverityAnomaly                             | 10000                |
      | mediaUploadMinimumSeverityCornering                           | 20                   |
      | mediaUploadMinimumSeverityCornering                           | 0                    |
      | mediaUploadMinimumSeverityDistractedDriving                   | 0                    |
      | mediaUploadMinimumSeverityDistractedDriving                   | 20                   |
      | mediaUploadMinimumSeverityDrowsyDriving                       | 50                   |
      | mediaUploadMinimumSeverityDrowsyDriving                       | 100                  |
      | mediaUploadMinimumSeverityForwardCollisionWarningTTCThreshold | 0.1                  |
      | mediaUploadMinimumSeverityForwardCollisionWarningTTCThreshold | 10                   |
      | mediaUploadMinimumSeverityHarshAcceleration                   | 0                    |
      | mediaUploadMinimumSeverityHarshAcceleration                   | 20                   |
      | mediaUploadMinimumSeverityHarshBraking                        | 0                    |
      | mediaUploadMinimumSeverityHarshBraking                        | 20                   |
      | mediaUploadMinimumSeverityMaxSpeed                            | 0                    |
      | mediaUploadMinimumSeverityMaxSpeed                            | 50                   |
      | mediaUploadMinimumSeverityPotentialCrash                      | 0                    |
      | mediaUploadMinimumSeverityPotentialCrash                      | 50                   |
      | mediaUploadMinimumSeveritySpeeding                            | 0                    |
      | mediaUploadMinimumSeveritySpeeding                            | 50                   |
      | mediaUploadMinimumSeverityStopSignViolation                   | 0                    |
      | mediaUploadMinimumSeverityStopSignViolation                   | 25                   |
      | mediaUploadMinimumSeverityTailgating                          | 0                    |
      | mediaUploadMinimumSeverityTailgating                          | 200                  |
      | minimumPostedSpeedEnforced                                    | 0                    |
      | minimumPostedSpeedEnforced                                    | 50                   |
      | noPowerSupplyNotificationLEDAltColor                          | green                |
      | noPowerSupplyNotificationLEDAltColor                          | yellow               |
      | noPowerSupplyNotificationLEDAltPulseDuration                  | 10                   |
      | noPowerSupplyNotificationLEDAltPulseDuration                  | 20000                |
      | noPowerSupplyNotificationLEDColor                             | green                |
      | noPowerSupplyNotificationLEDColor                             | yellow               |
      | noPowerSupplyNotificationLEDMode                              | pulse                |
      | noPowerSupplyNotificationLEDMode                              | constant             |
      | noPowerSupplyNotificationLEDPulseDuration                     | 10                   |
      | noPowerSupplyNotificationLEDPulseDuration                     | 20000                |
      | periodicImageCaptureDriverCameraQuality                       | 0                    |
      | periodicImageCaptureDriverCameraQuality                       | 10                   |
      | periodicImageCaptureDriverCameraResolution                    | 320x180              |
      | periodicImageCaptureDriverCameraResolution                    | 1920x1080            |
      | periodicImageCaptureEnabled                                   | true                 |
      | periodicImageCaptureEnabled                                   | false                |
      | periodicImageCaptureImageType                                 | pictureInPicture     |
      | periodicImageCaptureImageType                                 | sideBySide           |
      | periodicImageCaptureImageTypeMainFrame                        | road                 |
      | periodicImageCaptureImageTypeMainFrame                        | driver               |
      | periodicImageCaptureIntervalSeconds                           | 120                  |
      | periodicImageCaptureIntervalSeconds                           | 3600                 |
      | periodicImageCaptureQuality                                   | 0                    |
      | periodicImageCaptureQuality                                   | 10                   |
      | periodicImageCaptureResolution                                | 320x180              |
      | periodicImageCaptureResolution                                | 1920x1080            |
      | pitchDistractionSpeedThresholdMph                             | 0                    |
      | pitchDistractionSpeedThresholdMph                             | 10                   |
      | postEventVideoDurationAnomaly                                 | 2                    |
      | postEventVideoDurationAnomaly                                 | 50                   |
      | postEventVideoDurationCellphoneDistraction                    | 3                    |
      | postEventVideoDurationCellphoneDistraction                    | 50                   |
      | postEventVideoDurationCornering                               | 2                    |
      | postEventVideoDurationCornering                               | 50                   |
      | postEventVideoDurationCustomEvents                            | 5                    |
      | postEventVideoDurationCustomEvents                            | 30                   |
      | postEventVideoDurationDistractedDriving                       | 3                    |
      | postEventVideoDurationDistractedDriving                       | 50                   |
      | postEventVideoDurationDrowsyDriving                           | 1                    |
      | postEventVideoDurationDrowsyDriving                           | 50                   |
      | postEventVideoDurationForwardCollisionWarning                 | 2                    |
      | postEventVideoDurationForwardCollisionWarning                 | 50                   |
      | postEventVideoDurationHardBraking                             | 2                    |
      | postEventVideoDurationHardBraking                             | 50                   |
      | postEventVideoDurationHarshAcceleration                       | 2                    |
      | postEventVideoDurationHarshAcceleration                       | 50                   |
      | postEventVideoDurationLaneDeparture                           | 2                    |
      | postEventVideoDurationLaneDeparture                           | 50                   |
      | postEventVideoDurationLaneDrift                               | 2                    |
      | postEventVideoDurationLaneDrift                               | 50                   |
      | postEventVideoDurationMaxSpeed                                | 2                    |
      | postEventVideoDurationMaxSpeed                                | 50                   |
      | postEventVideoDurationPotentialCrash                          | 2                    |
      | postEventVideoDurationPotentialCrash                          | 50                   |
      | postEventVideoDurationSpeeding                                | 1                    |
      | postEventVideoDurationSpeeding                                | 50                   |
      | postEventVideoDurationStopSign                                | 1                    |
      | postEventVideoDurationStopSign                                | 50                   |
      | postEventVideoDurationTailgating                              | 2                    |
      | postEventVideoDurationTailgating                              | 50                   |
      | potentialCrashEDVREnabled                                     | true                 |
      | potentialCrashEDVREnabled                                     | false                |
      | potentialCrashEnabled                                         | true                 |
      | potentialCrashEnabled                                         | false                |
      | potentialCrashEventVideoType                                  | pictureInPicture     |
      | potentialCrashEventVideoType                                  | sideBySide           |
      | potentialCrashSpeedThreshold                                  | 10                   |
      | potentialCrashSpeedThreshold                                  | 100                  |
      | potentialCrashThreshold                                       | 5                    |
      | potentialCrashThreshold                                       | 200                  |
      | preEventVideoDurationAnomaly                                  | 5                    |
      | preEventVideoDurationAnomaly                                  | 9                    |
      | preEventVideoDurationCellphoneDistraction                     | 7                    |
      | preEventVideoDurationCellphoneDistraction                     | 9                    |
      | preEventVideoDurationCornering                                | 5                    |
      | preEventVideoDurationCornering                                | 9                    |
      | preEventVideoDurationCustomEvents                             | 5                    |
      | preEventVideoDurationCustomEvents                             | 30                   |
      | preEventVideoDurationDistractedDriving                        | 7                    |
      | preEventVideoDurationDistractedDriving                        | 9                    |
      | preEventVideoDurationDrowsyDriving                            | 3                    |
      | preEventVideoDurationDrowsyDriving                            | 9                    |
      | preEventVideoDurationForwardCollisionWarning                  | 5                    |
      | preEventVideoDurationForwardCollisionWarning                  | 9                    |
      | preEventVideoDurationHardBraking                              | 5                    |
      | preEventVideoDurationHardBraking                              | 9                    |
      | preEventVideoDurationHarshAcceleration                        | 5                    |
      | preEventVideoDurationHarshAcceleration                        | 9                    |
      | preEventVideoDurationLaneDeparture                            | 3                    |
      | preEventVideoDurationLaneDeparture                            | 9                    |
      | preEventVideoDurationLaneDrift                                | 5                    |
      | preEventVideoDurationLaneDrift                                | 9                    |
      | preEventVideoDurationMaxSpeed                                 | 5                    |
      | preEventVideoDurationMaxSpeed                                 | 9                    |
      | preEventVideoDurationPotentialCrash                           | 7                    |
      | preEventVideoDurationPotentialCrash                           | 9                    |
      | preEventVideoDurationSpeeding                                 | 9                    |
      | preEventVideoDurationSpeeding                                 | 9                    |
      | preEventVideoDurationStopSign                                 | 9                    |
      | preEventVideoDurationStopSign                                 | 9                    |
      | preEventVideoDurationTailgating                               | 5                    |
      | preEventVideoDurationTailgating                               | 9                    |
      | serialPortUsageType                                           | fuelRead             |
      | serialPortUsageType                                           | unused               |
      | shutdownNotificationLEDAltColor                               | green                |
      | shutdownNotificationLEDAltColor                               | yellow               |
      | shutdownNotificationLEDAltPulseDuration                       | 10                   |
      | shutdownNotificationLEDAltPulseDuration                       | 20000                |
      | shutdownNotificationLEDColor                                  | green                |
      | shutdownNotificationLEDColor                                  | yellow               |
      | shutdownNotificationLEDMode                                   | pulse                |
      | shutdownNotificationLEDMode                                   | constant             |
      | shutdownNotificationLEDPulseDuration                          | 10                   |
      | shutdownNotificationLEDPulseDuration                          | 20000                |
      | shutDownTimeAfterIgnitionOff                                  | 60                   |
      | shutDownTimeAfterIgnitionOff                                  | 1200                 |
      | speedCapEnabled                                               | true                 |
      | speedCapEnabled                                               | false                |
      | speedingAllowance                                             | 0                    |
      | speedingAllowance                                             | 40                   |
      | speedingEDVREnabled                                           | true                 |
      | speedingEDVREnabled                                           | false                |
      | speedingEnabled                                               | true                 |
      | speedingEnabled                                               | false                |
      | speedingEventVideoType                                        | pictureInPicture     |
      | speedingEventVideoType                                        | sideBySide           |
      | speedUpperLimit                                               | 0                    |
      | speedUpperLimit                                               | 150                  |
      | stopSignEDVREnabled                                           | true                 |
      | stopSignEDVREnabled                                           | false                |
      | stopSignEnabled                                               | true                 |
      | stopSignEnabled                                               | false                |
      | stopSignEventVideoType                                        | pictureInPicture     |
      | stopSignEventVideoType                                        | sideBySide           |
      | stopSignMaximumSpeed                                          | 0.5                  |
      | stopSignMaximumSpeed                                          | 20                   |
      | suspendUponIgnitionOff                                        | true                 |
      | suspendUponIgnitionOff                                        | false                |
      | tailgatingEDVREnabled                                         | true                 |
      | tailgatingEDVREnabled                                         | false                |
      | tailgatingEnabled                                             | true                 |
      | tailgatingEnabled                                             | false                |
      | tailgatingEventVideoType                                      | pictureInPicture     |
      | tailgatingEventVideoType                                      | sideBySide           |
      | tailgatingSensitivity                                         | 1                    |
      | tailgatingSensitivity                                         | 5                    |
      | tailgatingTimeThreshold                                       | 10                   |
      | tailgatingTimeThreshold                                       | 30                   |
      | tailgatingTTCThreshold                                        | 0.25                 |
      | tailgatingTTCThreshold                                        | 3                    |
      | timeToMonitorForStopSignViolation                             | 8                    |
      | timeToMonitorForStopSignViolation                             | 16                   |
      | triggerMinimumSeverityDistractedDriving                       | 30                   |
      | triggerMinimumSeverityDistractedDriving                       | 90                   |
      | triggerMinimumSpeedCellphoneDistractionMph                    | 0                    |
      | triggerMinimumSpeedCellphoneDistractionMph                    | 25                   |
      | triggerMinimumSpeedDrowsinessMph                              | 0                    |
      | triggerMinimumSpeedDrowsinessMph                              | 20                   |
      | triggerMinimumSpeedForwardCollisionWarningMph                 | 30                   |
      | triggerMinimumSpeedForwardCollisionWarningMph                 | 50                   |
      | triggerMinimumSpeedLaneDriftMph                               | 30                   |
      | triggerMinimumSpeedLaneDriftMph                               | 50                   |
      | triggerMinimumSpeedTailgatingMph                              | 30                   |
      | triggerMinimumSpeedTailgatingMph                              | 50                   |
      | tripMonitoringNotificationLEDAltColor                         | magenta              |
      | tripMonitoringNotificationLEDAltColor                         | yellow               |
      | tripMonitoringNotificationLEDAltPulseDuration                 | 10                   |
      | tripMonitoringNotificationLEDAltPulseDuration                 | 60000                |
      | tripMonitoringNotificationLEDColor                            | green                |
      | tripMonitoringNotificationLEDColor                            | yellow               |
      | tripMonitoringNotificationLEDMode                             | pulse                |
      | tripMonitoringNotificationLEDMode                             | constant             |
      | tripMonitoringNotificationLEDPulseDuration                    | 10                   |
      | tripMonitoringNotificationLEDPulseDuration                    | 20000                |
      | unassignedTripsWarningNotificationLEDAltColor                 | green                |
      | unassignedTripsWarningNotificationLEDAltColor                 | yellow               |
      | unassignedTripsWarningNotificationLEDAltPulseDuration         | 10                   |
      | unassignedTripsWarningNotificationLEDAltPulseDuration         | 60000                |
      | unassignedTripsWarningNotificationLEDColor                    | green                |
      | unassignedTripsWarningNotificationLEDColor                    | yellow               |
      | unassignedTripsWarningNotificationLEDMode                     | pulse                |
      | unassignedTripsWarningNotificationLEDMode                     | constant             |
      | unassignedTripsWarningNotificationLEDPulseDuration            | 10                   |
      | unassignedTripsWarningNotificationLEDPulseDuration            | 20000                |
      | useAccessPoints                                               | true                 |
      | useAccessPoints                                               | false                |
      | useExternalCameraForDMS                                       | true                 |
      | useExternalCameraForDMS                                       | false                |
      | useExternalUVCCameraForDMS                                    | true                 |
      | useExternalUVCCameraForDMS                                    | false                |
      | useGrayscaleDriverCamera                                      | true                 |
      | useGrayscaleDriverCamera                                      | false                |
      | useLongExposureCapture                                        | true                 |
      | useLongExposureCapture                                        | false                |
      | useMqttForLiveTelematics                                      | true                 |
      | useMqttForLiveTelematics                                      | false                |
      | usePreviousLaneCalibration                                    | true                 |
      | usePreviousLaneCalibration                                    | false                |
      | useStaticEndpointForDVR                                       | true                 |
      | useStaticEndpointForDVR                                       | false                |
      | warningMinimumSeverityDistractedDriving                       | 30                   |
      | warningMinimumSeverityDistractedDriving                       | 90                   |
      | wiggleSensorAccelerometerThreshold                            | 0.01                 |
      | wiggleSensorAccelerometerThreshold                            | 100                  |
      | wiggleSensorEnabled                                           | true                 |
      | wiggleSensorEnabled                                           | false                |
      | wiggleSensorIgnitionOffCheckMinimumDurationSeconds            | 15                   |
      | wiggleSensorIgnitionOffCheckMinimumDurationSeconds            | 600                  |
      | wiggleSensorIgnitionOffSpeedThresholdLowerMph                 | 1                    |
      | wiggleSensorIgnitionOffSpeedThresholdLowerMph                 | 10                   |
      | wiggleSensorShortTripDistanceThresholdMiles                   | 1                    |
      | wiggleSensorShortTripDistanceThresholdMiles                   | 2                    |
      | wiggleSensorShortTripTimeThresholdSeconds                     | 0                    |
      | wiggleSensorShortTripTimeThresholdSeconds                     | 600                  |
      | wiggleSensorVehicleType                                       | 0                    |
      | wiggleSensorVehicleType                                       | 7                    |
      | yawDistractionSpeedThresholdMph                               | 0                    |
      | yawDistractionSpeedThresholdMph                               | 100                  |
      | enableDataThrottle                                            | true                 |
      | enableDataThrottle                                            | false                |
      | simDataPlanLimit                                              | 256                  |
      | simDataPlanLimit                                              | 131072               |
      | simDataCycleStartDate                                         | 1                    |
      | simDataCycleStartDate                                         | 31                   |
      | timeInMinsForBadMountingRoadDetection                         | 30                   |
      | timeInMinsForBadMountingRoadDetection                         | 180                  |
      | dvrAudioEnabled                                               | true                 |
      | dvrAudioEnabled                                               | false                |
      | preEventVideoDurationSmokingDistraction                       | 5                    |
      | preEventVideoDurationSmokingDistraction                       | 9                    |
      | preEventVideoDurationDrinkingDistraction                      | 5                    |
      | preEventVideoDurationDrinkingDistraction                      | 9                    |
      | postEventVideoDurationSmokingDistraction                      | 2                    |
      | postEventVideoDurationSmokingDistraction                      | 50                   |
      | postEventVideoDurationDrinkingDistraction                     | 2                    |
      | postEventVideoDurationDrinkingDistraction                     | 50                   |
      | eventVideoResolutionSmokingDistraction                        | 320x180              |
      | eventVideoResolutionSmokingDistraction                        | 640x360              |
      | eventVideoResolutionSmokingDistraction                        | 1280x720             |
      | eventVideoResolutionSmokingDistraction                        | 1920x1080            |
      | eventVideoResolutionDrinkingDistraction                       | 320x180              |
      | eventVideoResolutionDrinkingDistraction                       | 640x360              |
      | eventVideoResolutionDrinkingDistraction                       | 1280x720             |
      | eventVideoResolutionDrinkingDistraction                       | 1920x1080            |
      | eventVideoQualitySmokingDistraction                           | 10                   |
      | eventVideoQualitySmokingDistraction                           | 0                    |
      | eventVideoQualityDrinkingDistraction                          | 10                   |
      | eventVideoQualityDrinkingDistraction                          | 0                    |
      | eventVideoDriverCameraResolutionSmokingDistraction            | 320x180              |
      | eventVideoDriverCameraResolutionSmokingDistraction            | 640x360              |
      | eventVideoDriverCameraResolutionSmokingDistraction            | 1280x720             |
      | eventVideoDriverCameraResolutionDrinkingDistraction           | 320x180              |
      | eventVideoDriverCameraResolutionDrinkingDistraction           | 640x360              |
      | eventVideoDriverCameraResolutionDrinkingDistraction           | 1280x720             |
      | eventVideoDriverCameraQualitySmokingDistraction               | 10                   |
      | eventVideoDriverCameraQualitySmokingDistraction               | 0                    |
      | eventVideoDriverCameraQualityDrinkingDistraction              | 10                   |
      | eventVideoDriverCameraQualityDrinkingDistraction              | 0                    |
      | captureMediaOnEventSmokingDistraction                         | true                 |
      | captureMediaOnEventSmokingDistraction                         | false                |
      | captureMediaOnEventDrinkingDistraction                        | true                 |
      | captureMediaOnEventDrinkingDistraction                        | false                |
      | smokingDistractionEDVREnabled                                 | true                 |
      | smokingDistractionEDVREnabled                                 | false                |
      | drinkingDistractionEDVREnabled                                | true                 |
      | drinkingDistractionEDVREnabled                                | false                |
      | smokingDistractionEventVideoType                              | road                 |
      | smokingDistractionEventVideoType                              | separate             |
      | smokingDistractionEventVideoType                              | pictureInPicture     |
      | smokingDistractionEventVideoType                              | driver               |
      | smokingDistractionEventVideoType                              | sideBySide           |
      | drinkingDistractionEventVideoType                             | road                 |
      | drinkingDistractionEventVideoType                             | separate             |
      | drinkingDistractionEventVideoType                             | pictureInPicture     |
      | drinkingDistractionEventVideoType                             | driver               |
      | drinkingDistractionEventVideoType                             | sideBySide           |
      | eventMediaTypeSmokingDistraction                              | video                |
      | eventMediaTypeSmokingDistraction                              | image                |
      | eventMediaTypeSmokingDistraction                              | none                 |
      | eventMediaTypeDrinkingDistraction                             | video                |
      | eventMediaTypeDrinkingDistraction                             | image                |
      | eventMediaTypeDrinkingDistraction                             | none                 |
      | sceneSpeedEstimationSpeedDifferentialInMph                    | 10                   |
      | sceneSpeedEstimationSpeedDifferentialInMph                    | 100                  |
      | enableDetectionOfDriverFaceBasedOnDriveSideZone               | true                 |
      | enableDetectionOfDriverFaceBasedOnDriveSideZone               | false                |
      | forceTimezone                                                 | true                 |
      | forceTimezone                                                 | false                |
      | forcedTimezoneOffsetInMins                                    | 0                    |
      | forcedTimezoneOffsetInMins                                    | 100                  |
      | numOfDaysOfInactivityForShutdown                              | 0                    |
      | numOfDaysOfInactivityForShutdown                              | 30                   |
      | disableAllWirelessBroadcasts                                  | true                 |
      | disableAllWirelessBroadcasts                                  | false                |
      | lizardEyeDistractionEnabled                                   | true                 |
      | lizardEyeDistractionEnabled                                   | false                |
      | enableSeatBeltNonCompliance                                   | true                 |
      | enableSeatBeltNonCompliance                                   | false                |
      | preEventVideoDurationLizardEyeDistraction                     | 9                    |
      | preEventVideoDurationLizardEyeDistraction                     | 9                    |
      | preEventVideoDurationSeatBeltNonCompliance                    | 9                    |
      | preEventVideoDurationSeatBeltNonCompliance                    | 9                    |
      | postEventVideoDurationLizardEyeDistraction                    | 6                    |
      | postEventVideoDurationLizardEyeDistraction                    | 6                    |
      | postEventVideoDurationSeatBeltNonCompliance                   | 6                    |
      | postEventVideoDurationSeatBeltNonCompliance                   | 6                    |
      | eventVideoResolutionLizardEyeDistraction                      | 640x360              |
      | eventVideoResolutionLizardEyeDistraction                      | 640x360              |
      | eventVideoResolutionSeatBeltNonCompliance                     | 640x360              |
      | eventVideoResolutionSeatBeltNonCompliance                     | 640x360              |
      | eventVideoQualityLizardEyeDistraction                         | 10                   |
      | eventVideoQualityLizardEyeDistraction                         | 1                    |
      | eventVideoQualitySeatBeltNonCompliance                        | 1                    |
      | eventVideoQualitySeatBeltNonCompliance                        | 10                   |
      | eventVideoDriverCameraResolutionLizardEyeDistraction          | 640x360              |
      | eventVideoDriverCameraResolutionLizardEyeDistraction          | 640x360              |
      | eventVideoDriverCameraResolutionSeatBeltNonCompliance         | 640x360              |
      | eventVideoDriverCameraResolutionSeatBeltNonCompliance         | 640x360              |
      | eventVideoDriverCameraQualityLizardEyeDistraction             | 1                    |
      | eventVideoDriverCameraQualityLizardEyeDistraction             | 10                   |
      | eventVideoDriverCameraQualitySeatBeltNonCompliance            | 1                    |
      | eventVideoDriverCameraQualitySeatBeltNonCompliance            | 10                   |
      | captureMediaOnEventLizardEyeDistraction                       | true                 |
      | captureMediaOnEventLizardEyeDistraction                       | false                |
      | captureMediaOnEventSeatBeltNonCompliance                      | true                 |
      | captureMediaOnEventSeatBeltNonCompliance                      | false                |
      | lizardEyeDistractionEDVREnabled                               | true                 |
      | lizardEyeDistractionEDVREnabled                               | false                |
      | seatBeltNonComplianceEDVREnabled                              | true                 |
      | seatBeltNonComplianceEDVREnabled                              | false                |
      | eventMediaTypeLizardEyeDistraction                            | image                |
      | eventMediaTypeLizardEyeDistraction                            | video                |
      | eventMediaTypeSeatBeltNonCompliance                           | image                |
      | eventMediaTypeSeatBeltNonCompliance                           | video                |
      | lizardEyeDistractionEventVideoType                            | road                 |
      | lizardEyeDistractionEventVideoType                            | driver               |
      | lizardEyeDistractionEventVideoType                            | sideBySide           |
      | lizardEyeDistractionEventVideoType                            | pictureInPicture     |
      | lizardEyeDistractionEventVideoType                            | separate             |
      | seatBeltNonComplianceEventVideoType                           | road                 |
      | seatBeltNonComplianceEventVideoType                           | driver               |
      | seatBeltNonComplianceEventVideoType                           | sideBySide           |
      | seatBeltNonComplianceEventVideoType                           | pictureInPicture     |
      | seatBeltNonComplianceEventVideoType                           | separate             |
      | minYawDistractionDurationSeconds                              | 3                    |
      | minYawDistractionDurationSeconds                              | 10                   |
      | minimumPitchDistractionDurationSeconds                        | 2                    |
      | minimumPitchDistractionDurationSeconds                        | 10                   |
      | minDistractionDurationShortPitch                              | 3                    |
      | minDistractionDurationShortPitch                              | 20                   |
      | minDurationThresholdForSeatBeltNonCompliance                  | 20                   |
      | minDurationThresholdForSeatBeltNonCompliance                  | 60                   |
      | preEventVideoDurationTextingDistraction                       | 9                    |
      | preEventVideoDurationTextingDistraction                       | 9                    |
      | postEventVideoDurationTextingDistraction                      | 9                    |
      | postEventVideoDurationTextingDistraction                      | 9                    |
      | eventVideoResolutionTextingDistraction                        | 640x360              |
      | eventVideoResolutionTextingDistraction                        | 640x360              |
      | eventVideoDriverCameraResolutionTextingDistraction            | 640x360              |
      | eventVideoDriverCameraResolutionTextingDistraction            | 640x360              |
      | eventVideoDriverCameraQualityTextingDistraction               | 1                    |
      | eventVideoDriverCameraQualityTextingDistraction               | 10                   |
      | captureMediaOnEventTextingDistraction                         | true                 |
      | captureMediaOnEventTextingDistraction                         | false                |
      | textingDistractionEDVREnabled                                 | true                 |
      | textingDistractionEDVREnabled                                 | false                |
      | eventMediaTypeTextingDistraction                              | image                |
      | eventMediaTypeTextingDistraction                              | video                |
      | textingDistractionEventVideoType                              | road                 |
      | textingDistractionEventVideoType                              | driver               |
      | textingDistractionEventVideoType                              | sideBySide           |
      | textingDistractionEventVideoType                              | pictureInPicture     |
      | textingDistractionEventVideoType                              | separate             |
      | minEyeCloseDurationForLizardEye                               | 3                    |
      | minEyeCloseDurationForLizardEye                               | 20                   |
      | minEyeCloseDurationForDrowsiness                              | 1                    |
      | minEyeCloseDurationForDrowsiness                              | 10                   |
      | minDurationThresholdForCellphone                              | 3                    |
      | minDurationThresholdForCellphone                              | 10                   |
      | minDurationThresholdForSmoking                                | 20                   |
      | minDurationThresholdForSmoking                                | 60                   |
      | minDurationThresholdForDrinking                               | 3                    |
      | minDurationThresholdForDrinking                               | 10                   |
      | minDurationThresholdForTexting                                | 3                    |
      | minDurationThresholdForTexting                                | 10                   |
      | triggerMinimumSpeedLizardEyeDistractionMph                    | 0                    |
      | triggerMinimumSpeedLizardEyeDistractionMph                    | 100                  |
      | triggerMinimumSpeedSeatBeltNonCompliance                      | 0                    |
      | triggerMinimumSpeedSeatBeltNonCompliance                      | 100                  |
      | minimumDistanceForMediaUploadDistractedDrivingMetres          | 0                    |
      | minimumDistanceForMediaUploadDistractedDrivingMetres          | 1500                 |
      | minimumDistanceForMediaUploadDrowsyDrivingMetres              | 0                    |
      | minimumDistanceForMediaUploadDrowsyDrivingMetres              | 800                  |
      | minimumDistanceForMediaUploadLizardEyeDistractionMetres       | 0                    |
      | minimumDistanceForMediaUploadLizardEyeDistractionMetres       | 1500                 |
      | minimumDistanceForMediaUploadCellphoneDistractionMeters       | 0                    |
      | minimumDistanceForMediaUploadCellphoneDistractionMeters       | 2400                 |
      | minimumDistanceForMediaUploadSmokingDistractionMeters         | 0                    |
      | minimumDistanceForMediaUploadSmokingDistractionMeters         | 2400                 |
      | minimumDistanceForMediaUploadDrinkingDistractionMeters        | 0                    |
      | minimumDistanceForMediaUploadDrinkingDistractionMeters        | 2400                 |
      | minimumDistanceForMediaUploadTextingDistractionMeters         | 0                    |
      | minimumDistanceForMediaUploadTextingDistractionMeters         | 2400                 |
      | laneDetectDeviationMultiplier                                 | 1                    |
      | laneDetectDeviationMultiplier                                 | 1                    |
      | laneDetectDeviationQuanta                                     | 1                    |
      | laneDetectDeviationQuanta                                     | 1                    |
      | laneDriftDuration                                             | 10                   |
      | laneDriftDuration                                             | 10                   |
      | laneDriftDetectFrameCount                                     | 6                    |
      | laneDriftDetectFrameCount                                     | 6                    |
      | laneDriftSilentTime                                           | 35                   |
      | laneDriftSilentTime                                           | 35                   |
      | laneDepartureWaitTime                                         | 60                   |
      | laneDepartureWaitTime                                         | 90                   |
      | maxYawThresholdSeatBelt                                       | 0                    |
      | maxYawThresholdSeatBelt                                       | 90                   |
      | seatBeltFrameLevelThreshold                                   | 0.65                 |
      | seatBeltFrameLevelThreshold                                   | 0.65                 |
      | seatBeltTemporalLevelThreshold                                | 0.5                  |
      | seatBeltTemporalLevelThreshold                                | 0.5                  |
      | minYawThresholdSeatBelt                                       | -90                  |
      | minYawThresholdSeatBelt                                       | 0                    |
      | yawDeviationThresholdDegrees                                  | 15                   |
      | yawDeviationThresholdDegrees                                  | 60                   |
      | pitchDeviationThresholdDegrees                                | 5                    |
      | pitchDeviationThresholdDegrees                                | 25                   |
      | enableFullFrameImageCaptureForSceneSpeedEstimator             | true                 |
      | enableFullFrameImageCaptureForSceneSpeedEstimator             | false                |
      | networkConnectedNotificationLEDAltColor                       | black                |
      | networkConnectedNotificationLEDAltColor                       | green                |
      | networkConnectedNotificationLEDAltPulseDuration               | 15000                |
      | networkConnectedNotificationLEDAltPulseDuration               | 3000                 |
      | networkConnectedNotificationLEDColor                          | black                |
      | networkConnectedNotificationLEDColor                          | green                |
      | networkConnectedNotificationLEDMode                           | constant             |
      | networkConnectedNotificationLEDMode                           | pulse                |
      | networkConnectedNotificationLEDPulseDuration                  | 300                  |
      | networkConnectedNotificationLEDPulseDuration                  | 300                  |
      | unprovisionedWithNetworkNotificationLEDAltColor               | black                |
      | unprovisionedWithNetworkNotificationLEDAltColor               | green                |
      | unprovisionedWithNetworkNotificationLEDAltPulseDuration       | 0                    |
      | unprovisionedWithNetworkNotificationLEDAltPulseDuration       | 500                  |
      | unprovisionedWithNetworkNotificationLEDColor                  | blue                 |
      | unprovisionedWithNetworkNotificationLEDColor                  | white                |
      | unprovisionedWithNetworkNotificationLEDMode                   | pulse                |
      | unprovisionedWithNetworkNotificationLEDMode                   | constant             |
      | unprovisionedWithNetworkNotificationLEDPulseDuration          | 500                  |
      | unprovisionedWithNetworkNotificationLEDPulseDuration          | 500                  |
      | unprovisionedWithNoNetworkNotificationLEDAltColor             | black                |
      | unprovisionedWithNoNetworkNotificationLEDAltColor             | black                |
      | unprovisionedWithNoNetworkNotificationLEDAltPulseDuration     | 500                  |
      | unprovisionedWithNoNetworkNotificationLEDAltPulseDuration     | 500                  |
      | unprovisionedWithNoNetworkNotificationLEDColor                | blue                 |
      | unprovisionedWithNoNetworkNotificationLEDColor                | black                |
      | unprovisionedWithNoNetworkNotificationLEDMode                 | constant             |
      | unprovisionedWithNoNetworkNotificationLEDMode                 | pulse                |
      | unprovisionedWithNoNetworkNotificationLEDPulseDuration        | 500                  |
      | unprovisionedWithNoNetworkNotificationLEDPulseDuration        | 500
